/**
 * 定义应用路由（登录系统用）
 */
import React from 'react';
import {
  Router,
  // browserHistory,
  hashHistory,
} from 'react-router';
import { Provider } from 'react-redux'
import store from './store'

import DefaultM from './pages/Account';
const autoGeneratedRoutes = [{
  path: '/(:from)',
  indexRoute: {
    component: DefaultM.Account
  }
}];

import AccountRoute from "./pages/Account/AccountRoute.js"
let myCustomRoutes = [AccountRoute];

export default (
  <Provider store={store}>
    <Router
      history={hashHistory}
      routes={[...autoGeneratedRoutes, ...myCustomRoutes]}
    />
  </Provider>
);
